sprint1/step2
katokinawa/burger-adventure pull request #1
Opened 2024-12-26 07:35 UTC by katokinawa

The header and homepage have been created, the modal window is completed, and we are successfully sending requests to the server while also handling errors in case of request failures

2024-12-26 08:21 UTC, SergeyK2004 requested changes
Здравствуйте. 

Вы проделали большую работу, что мне понравилось:

* Хорошо выполнена верстка
* Корректно используются семанитические теги для разных областей страницы.
* Использование пустого массива зависимостей [] в useEffect 
* Использование атрибута key, и здорово, что для него вы используете уникальный _id, а не индекс массива.

но есть некоторые недочеты:

* Клик в табы должен скролить список ингредиентов к нужному разделу, а не менять сортировку групп ингредиентов.
* Тип для ингредиента (propTypes) повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу IngredientType в отдельный файл types.js в папку utils и импортировать туда, где нужно
* Любой ответ от сервера нужно проверять на ok(на корректность) и вызывать ошибку, если ответ не ok. Таким образом, в catch Вы будете ловить и ошибки сервера, и ошибки невалидных данных.

Исправьте указанные недочеты и работа будет принята.

2024-12-26 08:21 UTC, SergeyK2004 commented on src/components/app/app.jsx
> +    .then(res => res.json())
**Надо исправить:**

Любой ответ от сервера нужно проверять на `ok` (на корректность) и вызывать ошибку, если ответ не `ok`. Таким образом, в `catch` Вы будете ловить и ошибки сервера, и ошибки невалидных данных.

```jsx
.then(res => {
                if (res.ok) {
                    return res.json();
                }
                return Promise.reject(`Ошибка ${res.status}`);
            })
```

2024-12-26 08:21 UTC, SergeyK2004 commented on src/components/modal/modal.jsx
> +  function handlePressKey(evt) {
Функцию обработчик следует переместить внутрь useEffect(), чтобы функция не пересоздавалась при каждом рендере.

2024-12-26 08:21 UTC, SergeyK2004 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const [isModalOpen, setIsModalOpen] = useState(false);
Можно лучше

Если интересно, можно создать кастомный хук для управления модальным окном:

```jsx
import { useState, useCallback } from "react";

// кастомные хуки всегда должны начинаться с глагола `use`, чтобы реакт понял, что это хук. Он следит за их вызовами
export const useModal = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);

  // `useCallback` нужен для того, чтобы зафиксировать ссылку на функцию. Таким образом уменьшится кол-во перерисовок компонента, куда будет передана эта функция
  const openModal = useCallback(() => {
    setIsModalOpen(true);
  }, []);

  const closeModal = useCallback(() => {
    setIsModalOpen(false);
  }, []);

  return {
    isModalOpen,
    openModal,
    closeModal,
  };
};
```

Этот код помещают в отдельный файл useModal.js в папке hooks и импортируют функцию туда, где нужно создать показатели открытости/закрытости попапа (у каждого попапа они свои)

И теперь нужно просто вызывать хук в том компоненте, где нужно управлять попапом. Всего одна строчка кода будет (под каждый попап своя):

```jsx
  const { isModalOpen, openModal, closeModal } = useModal();
```

2024-12-26 08:21 UTC, SergeyK2004 commented on src/components/burger-constructor/burger-constructor.jsx
> +    PropTypes.shape({
**Надо исправить:**

Тип для ингредиента (propTypes) повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу IngredientType в отдельный файл types.js в папку utils и импортировать туда, где нужно

2024-12-29 19:02 UTC, katokinawa commented
Привет! Я исправил замечания, которые ты мне дал на платформе, мёржу свою ветку в основную

2024-12-29 19:02 UTC, merged